name: Build
on:
  push:
    branches:
      - master
      - "6.7"
    paths-ignore:
      - "README.md"
      - "release-notes/*"
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - java_version: "8"
            os: "ubuntu-20.04"
            architecture: "x64"
          - java_version: "11"
            os: "ubuntu-20.04"
            architecture: "x64"
          - java_version: "17"
            os: "ubuntu-20.04"
            architecture: "x64"
          - java_version: "21"
            os: "ubuntu-20.04"
            architecture: "x64"
          - java_version: "8"
            os: "ubuntu-22.04-ppc64le"
            architecture: "ppc64le"
          - java_version: "11"
            os: "ubuntu-22.04-ppc64le"
            architecture: "ppc64le"
          - java_version: "17"
            os: "ubuntu-22.04-ppc64le"
            architecture: "ppc64le"
          - java_version: "21"
            os: "ubuntu-22.04-ppc64le"
            architecture: "ppc64le"
          - java_version: "8"
            os: "ubuntu-22.04"
            architecture: "x64"
          - java_version: "11"
            os: "ubuntu-22.04"
            architecture: "x64"
          - java_version: "17"
            os: "ubuntu-22.04"
            architecture: "x64"
          - java_version: "21"
            os: "ubuntu-22.04"
            architecture: "x64"

    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

    steps:
      - uses: actions/checkout@v4

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java_version }}
          architecture: ${{ matrix.architecture }}
          cache: "maven"
          server-id: sonatype-nexus-snapshots
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD

      - name: Build
        run: ./mvnw -B -q -ff -ntp verify

      - name: Generate code coverage
        if: github.event_name != 'pull_request' && matrix.java_version == '8'
        run: ./mvnw -B -ff -ntp test

      - name: Publish code coverage
        if: github.event_name != 'pull_request' && matrix.java_version == '8'
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests
